### PR TITLE
Support for Amazon Lex V2

### PR DESCRIPTION
**Pull request by palle-k**
## Proposed changes

This PR adds support for exporting and importing models with Amazon Lex V2. 
Addresses #70.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by palle-k** [comment]
Looking for support on how to generate the JSON Schemas. Running `npx gulp` currently outputs `null` to all files.

Furthermore, the following is printed to the console:

```
/<some-path>/jovo-model/packages/jovo-model-lexv2/node_modules/@jovotech/model/dist/src/index.d.ts (1,37): Cannot find module './validators/JovoModelValidator.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
/<some-path>/jovo-model/packages/jovo-model-lexv2/node_modules/@jovotech/model/dist/src/index.d.ts (2,39): Cannot find module './validators/JovoModelValidatorV3.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
```

**Comment by palle-k** [comment]
Also open to suggestions on how to allow the specification of Lex specifics for individual Intents and SlotTypes

**Comment by jrglg** [comment]
Thank you!

I'll have a look a it on monday

**Comment by jankoenig** [comment]
Thank you @palle-k 🎉  We're going to take a look in the next few days

**Comment by aswetlow** [comment]
Hey @palle-k 

It's my fault that it's taking so long. I found some issues on our side regarding the validation part.

**Comment by aswetlow** [comment]
Hey @palle-k 
Would it be possible to refactor `generateFiles` without using generator methods? It would be easier to maintain in the future since we're more experienced with `async/await` 😄

**Comment by palle-k** [comment]
@aswetlow sure, will do

**Comment by palle-k** [comment]
@aswetlow okay, I'm using an array to collect files now instead of a generator.

**Review by jankoenig — APPROVED** [review]
Thank you @palle-k 🎉

**Comment by jrglg** [comment]
I'm a bit confused on how to use Lex model v2 integration in Jovo.

I guess I have to convert the model first:
```
const jovoModelInstance = new JovoModelLex();
import jovoModelData from "./models/es.json";
const locale = 'es-ES';
jovoModelInstance.importJovoModel(jovoModelData, locale);
const lexModelFiles = jovoModelInstance.exportNative();
```
Then organize exported model in files, right?
Because Lex docs format is different from the generated by Jovo.

Thank you

**Comment by palle-k** [comment]
@jrglg I am noticing that you are using `JovoModelLex`, not `JovoModelLexV2` (make sure to install `@jovotech/model-lexv2` - just became available).

Secondly, `JovoModelLexV2` exports files that correspond to a bot locale of a Lex V2 bot. So for each `file` in `lexModelFiles`,  you have to save `file.content` to `file.path` (where each element of the path array is a path component). 

Note that the format actually differs slightly between the official Amazon Lex V2 documentation and what the Lex V2 upload actually accepts. 

To import the bot locale to Amazon Lex V2 using the AWS CLI:

1. Zip the directory containing all the exported files (`zip -r bot.zip exported_model_dir`)
2. `aws lexv2-models create-upload-url` > take the `uploadUrl` and `importId` parameters from the response JSON
3. `curl -X PUT -T './bot.zip' "<uploadUrl>"` (make sure to replace the variable `<uploadUrl>`)
4. `aws lexv2-models start-import --import-id "<importId>" --resource-specification "{\"botLocaleImportSpecification\": {\"botId\": \"<botId>\", \"botVersion\": \"DRAFT\", \"localeId\": \"es_ES\"}}" --merge-strategy Overwrite` (make sure to replace the variables `<botId>` and `<importId>`)
5. `aws lexv2-models wait bot-import-completed --import-id "<importId>"`
6. `aws lexv2-models delete-import --import-id "<importId>"`

**Comment by jrglg** [comment]
Thank you I could make it with your help.

I noticed that Jovo maps entity `value` of `Amazon.Date` differently in Lex/Alexa, which is weird I think.

Alexa:

```
"day": {
    "native": {
      "name": "day",
      "value": "2022-06-22",
      "confirmationStatus": "NONE",
      "source": "USER",
      "slotValue": {
        "type": "Simple",
        "value": "2022-06-22"
      }
    },
    "value": "2022-06-22",
    "resolved": "2022-06-22"
  }
}
``` 

Lex:

```
"day": {
  "id": "2022-06-22",
  "resolved": "2022-06-22",
  "value": "tomorrow",
  "native": {
    "value": {
      "interpretedValue": "2022-06-22",
      "originalValue": "tomorrow",
      "resolvedValues": [
        "2022-06-22"
      ]
    }
  }
}
```

**Pull request merged**
